// smoke テストのランナー（本体は scripts/smoke/ に分割。npm run smoke / smoke:quiet で実行）
// 新しいテストは scripts/smoke/ に partN.ts を追加してここに import を足す
import "./smoke/part1"
import "./smoke/part2"
import "./smoke/part3"
import "./smoke/part4"
import "./smoke/part5"
import "./smoke/part6"
import "./smoke/part7"
import "./smoke/part8"
import "./smoke/part9"
import "./smoke/part10"
import "./smoke/part11"
import "./smoke/part12"
import "./smoke/part13"
import "./smoke/part14"
import "./smoke/part15"
import "./smoke/part16"
import "./smoke/part17"
import "./smoke/part18"
import "./smoke/part19"
import "./smoke/part20"
import "./smoke/part21"
import { summary } from "./smoke/helpers"

summary()
